const normalquiz = [ { questiontype: '一問多答',
question: 'ルフィがシェルズタウンで使用した技を次のうちから全て選べ。',
options: [ 'ゴムゴムのロケット', 'ゴムゴムの銃乱打', 'ゴムゴムの銃', 'ゴムゴムの鞭' ],
correct: [ 'ゴムゴムのロケット', 'ゴムゴムの銃', 'ゴムゴムの鞭' ] },
{ questiontype: '一問一答',
question: 'バギーの好物を次のうちから一つ選べ。',
options: [ 'ポップコーン', 'トマト', 'ホットドッグ', '酒' ],
correct: 'ホットドッグ' },
 ];

const extraquiz = [ { questiontype: '一問多答',
question: 'ルフィがシェルズタウンで使用した技を次のうちから全て選べ。',
options: [ 'ゴムゴムのロケット', 'ゴムゴムの銃乱打', 'ゴムゴムの銃', 'ゴムゴムの鞭' ],
correct: [ 'ゴムゴムのロケット', 'ゴムゴムの銃', 'ゴムゴムの鞭' ] },
{ questiontype: '一問一答',
question: 'バギーの好物を次のうちから一つ選べ。',
options: [ 'ポップコーン', 'トマト', 'ホットドッグ', '酒' ],
correct: 'ホットドッグ' },
{ questiontype: '一問一答',
question: 'ゾロのセリフ「俺の野望ゆえ そして●●との約束のためだ」の●●に入る言葉を次のうちから一つ選べ。',
options: [ '仲間', '師匠', '親友', '船長' ],
correct: '親友' },
{ questiontype: '記述',
question: 'サンジを陥れる為、フルボディ大尉がスープに入れたハエの名前を答えよ。',
correct: 'バッチー' },
{ questiontype: '記述',
question: 'ゼフの帽子の名前を漢字で答えよ。',
correct: '青天割料理人帽' },
{ questiontype: '一問一答',
question: 'ヤソップのヘッドバンドに書かれていた文字を次のうちから一つ選べ。',
options: [ 'USOPP', 'YASOPP', 'SNIPER', 'PIRATE' ],
correct: 'YASOPP' },
{ questiontype: '一問一答',
question: 'アルビダのことを「この海で１番イカついクソばばあ」と言ったキャラクターを次のうちから一つ選べ。',
options: [ 'コビー', 'ルフィ', 'バギー', 'カバジ' ],
correct: 'コビー' },
{ questiontype: '一問一答',
question: 'ギンの役職を次のうちから一つ選べ。',
options: [ '戦闘総隊長', '特攻隊長', '雑用', '第１部隊 隊長' ],
correct: '戦闘総隊長' },
{ questiontype: '一問一答',
question: 'リヴァース・マウンテンは何島か次のうちから一つ選べ。',
options: [ '春島', '夏島', '秋島', '冬島' ],
correct: '冬島' },
{ questiontype: '記述',
question: 'ナミがリヴァース・マウンテンやその付近の海流について説明した後にルフィが言ったセリフ「ははーん 要するに〝 ████ 〟なんだな？」の空欄に入るセリフを答えよ。スペースや〝〟は不要だが、「！」や「・」などの記号は全て正確に記述することとする。',
correct: '不思議山' },
{ questiontype: '記述',
question: 'ルフィが「ちくわのおっさん」と呼ぶキャラクターの名前を答えよ。スペースや「！」「・」などの記号は不要とする。',
correct: 'イガラム' },
{ questiontype: '一問一答',
question: 'Dr.くれはが「行っといで バカ息子・・・」と言った153話のサブタイトルを次のうちから一つ選べ。',
options: [ 'ヒルルクの桜', '受け継がれる意志', '満月', 'ドラムの空' ],
correct: 'ヒルルクの桜' },
{ questiontype: '記述',
question: 'ロビンの技”六輪咲き〟の読み方をカタカナで答えよ。スペースや「！」「・」などの記号は不要とする。',
correct: 'セイスフルール' },
{ questiontype: '一問一答',
question: 'アラバスタ王国動物速脚ランキング2位の動物を次のうちから一つ選べ。',
options: [ 'F-ワニ', '超カルガモ', 'ヒッコシクラブ', 'エリマキランナーズ' ],
correct: 'F-ワニ' },
{ questiontype: '一問一答',
question: 'ドリーとブロギーの懸賞金の合計額を次のうちから一つ選べ。',
options: [ '1億', '2億', '3億', '4億' ],
correct: '2億' },
{ questiontype: '',
question: 'Mr.3の本名を答えよ。スペースや「！」「・」などの記号は不要とする。',
correct: 'ギャルディーノ' },
{ questiontype: '一問一答',
question: 'ウソップパウンドの総重量を次のうちから一つ選べ。',
options: [ '2kg', '3kg', '4kg', '5kg' ],
correct: '2kg' },
{ questiontype: '記述',
question: 'ビビの現在の年齢を数字だけで答えよ。',
correct: '１８' },
{ questiontype: '並べ替え',
question: '次の４つの選択肢を麦わらの一味が訪れた順に並び替えよ。',
options: [ 'ユバ', 'エルマル', 'レインベース', 'ナノハナ' ],
correct: [ 'ナノハナ', 'エルマル', 'ユバ', 'レインベース' ] },
{ questiontype: '記述',
question: 'クロコダイルの技「バルハン」を漢字で答えよ。スペースや「！」「・」などの記号は不要とする。',
correct: '三日月形砂丘' },
{ questiontype: '一問一答',
question: 'ネフェルタリ・コブラは第何代アラバスタ王国国王か。次のうちから一つ選べ。',
options: [ '第10代', '第11代', '第12代', '第13代' ],
correct: '第12代' },
{ questiontype: '一問一答',
question: 'アラバスタ東の港の名前を次のうちから一つ選べ。',
options: [ 'ヒガシリスク', 'バジリスク', 'イーストリスク', 'タマリスク' ],
correct: 'タマリスク' },
{ questiontype: '一問一答',
question: '黒ひげ海賊団ドクQの異名を次のうちから一つ選べ。',
options: [ '闇医者', 'ヤブ医者', '疫病神', '死神' ],
correct: '死神' },
{ questiontype: '一問一答',
question: 'サウスバードの鳴き声を次のうちから一つ選べ。',
options: [ 'ジャ〜', 'ジュ〜', 'ジョ〜', 'ジェ〜' ],
correct: 'ジョ〜' },
{ questiontype: '記述',
question: 'ワイパーの武器「バーンバズーカ」を漢字で答えよ。スペースや「！」「・」などの記号は不要とする。',
correct: '燃焼砲' },
{ questiontype: '',
question: 'スカイピアには存在しない貝を次の内から一つ選べ。',
options: [ '斬撃貝', '衝撃貝', '匂貝', '炎貝' ],
correct: '斬撃貝' },
{ questiontype: '',
question: 'シュラを撃破したゾロの技を次の内から一つ選べ。',
options: [ '三十六煩悩鳳', '百八煩悩鳳', '三百六十煩悩鳳', '千八十煩悩鳳' ],
correct: '百八煩悩鳳' },
{ questiontype: '一問一答',
question: 'ワポルが建国した国をカタカナと漢字で答えよ。スペースや「！」「・」などの記号は不要とする。',
correct: '悪ブラックドラム王国' } ];